In [15]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_regression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.ensemble import AdaBoostRegressor
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
dataset_train=pd.read_csv("C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\train.csv")
dataset_train.head()

id  season  mnth  holiday  weekday  workingday  weathersit      temp  \
0   1       1     1        0        6           0           2  0.344167   
1   2       1     1        0        0           0           2  0.363478   
2   3       1     1        0        1           1           1  0.196364   
3   4       1     1        0        2           1           1  0.200000   
4   5       1     1        0        3           1           1  0.226957   

      atemp       hum  windspeed   cnt  
0  0.363625  0.805833   0.160446   985  
1  0.353739  0.696087   0.248539   801  
2  0.189405  0.437273   0.248309  1349  
3  0.212122  0.590435   0.160296  1562  
4  0.229270  0.436957   0.186900  1600

In [17]:
X = dataset_train.iloc[:, 1:-1].values
y = dataset_train.iloc[:, -1].values

In [18]:
model = AdaBoostRegressor()

In [19]:
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)

In [20]:
n_scores = cross_val_score(model, X, y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1, error_score='raise')

In [26]:
print('MAE: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

MAE: -467.197 (73.574)


In [22]:
regressor = AdaBoostRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X,y)

AdaBoostRegressor(n_estimators=100, random_state=0)

In [28]:
y_pred = regressor.predict(X)
np.set_printoptions(precision=2)

In [29]:
y_pred

array([1589.46, 1458.75, 1541.83, 1460.69, 1541.83, 1611.62, 1651.15,
       1541.83, 1458.75, 1541.83, 1245.57, 1458.75, 1460.69, 1641.33,
       1655.79, 1460.69, 1460.69, 1140.  , 1317.14, 1568.47, 1622.27,
       1641.33, 1460.69, 1541.83, 1568.47,  762.37, 1169.6 , 1219.83,
       1589.46, 1373.65, 1460.69, 1460.69, 1317.14, 1611.62, 1690.77,
       1317.14, 1655.79, 1690.77, 1568.86, 1641.33, 1641.33, 1684.71,
       1655.79, 1798.06, 1995.04, 1641.33, 1847.46, 2879.64, 3597.  ,
       1959.15, 1655.79, 1611.62, 1611.62, 1684.71, 1373.65, 1663.91,
       1696.85, 1798.  , 1684.71, 1641.33, 1798.06, 1641.33, 1690.77,
       1660.64, 1405.24, 1571.94, 1821.14, 1386.73, 1565.12, 1931.  ,
       1995.04, 1849.76, 1849.76, 1887.95, 1611.62, 2682.11, 4199.76,
       3650.52, 1849.76, 2728.36, 3239.15, 1887.95, 1690.77, 2040.58,
       2050.16, 1958.88, 1987.04, 1995.04, 1995.04, 1411.64, 1847.46,
       2649.25, 2615.12, 3674.16, 2676.53, 2615.12, 3252.12, 2050.16,
       2199.63, 2990

In [30]:
dataset_test=pd.read_csv("C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\test.csv")
dataset_test.head()

id  season  mnth  holiday  weekday  workingday  weathersit      temp  \
0  366       1     1        0        0           0           1  0.370000   
1  367       1     1        1        1           0           1  0.273043   
2  368       1     1        0        2           1           1  0.150000   
3  369       1     1        0        3           1           2  0.107500   
4  370       1     1        0        4           1           1  0.265833   

      atemp       hum  windspeed  
0  0.375621  0.692500   0.192167  
1  0.252304  0.381304   0.329665  
2  0.126275  0.441250   0.365671  
3  0.119337  0.414583   0.184700  
4  0.278412  0.524167   0.129987

In [31]:
X2 = dataset_test.iloc[:, 1:].values
X2

array([[ 1.  ,  1.  ,  0.  , ...,  0.38,  0.69,  0.19],
       [ 1.  ,  1.  ,  1.  , ...,  0.25,  0.38,  0.33],
       [ 1.  ,  1.  ,  0.  , ...,  0.13,  0.44,  0.37],
       ...,
       [ 1.  , 12.  ,  0.  , ...,  0.24,  0.75,  0.12],
       [ 1.  , 12.  ,  0.  , ...,  0.23,  0.48,  0.35],
       [ 1.  , 12.  ,  0.  , ...,  0.22,  0.58,  0.15]])

In [32]:
len(X2)

366

In [33]:
y2_pred = regressor.predict(X2)
np.set_printoptions(precision=2)

In [36]:
y2_pred

array([1568.47, 1553.25, 1460.69, 1568.47, 1568.47, 1849.76, 1964.69,
       1768.11, 1340.8 , 1821.14, 1245.57, 1460.69, 1655.79, 1641.33,
       1460.69, 1460.69, 1450.57, 1568.86, 1541.83, 1651.15, 1217.37,
       1142.78, 1219.83, 1528.48, 1568.86, 1655.79, 2255.91, 1915.25,
       1571.94, 1611.62, 1758.12, 3993.77, 1987.04, 1933.56, 1373.65,
       1324.23, 1655.79, 1849.76, 1373.65, 1641.33, 1696.85,  908.15,
       1622.27, 1641.33, 1847.46, 1849.76, 1752.42, 1987.04, 1959.15,
       1641.33, 1641.33, 1655.79, 2163.19, 3166.86, 2557.53, 1735.  ,
       1655.79, 1798.06, 1849.76, 1611.62, 3940.08, 1933.56, 2661.14,
       1798.06, 1655.79, 1655.79, 1887.95, 3503.94, 1987.04, 1735.  ,
       1849.76, 3993.77, 4199.76, 4256.55, 4256.55, 2826.46, 3799.47,
       3546.76, 4186.23, 3955.48, 3692.67, 4003.27, 4686.16, 3450.07,
       2842.38, 3209.99, 2356.79, 3659.37, 3659.37, 2643.9 , 2915.51,
       3109.63, 3191.84, 4256.55, 4513.94, 3295.24, 2826.46, 3252.12,
       4511.19, 3857

In [37]:
submission=pd.read_csv("C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\sample_submission.csv")
submission.head()

id          cnt
0  366  2324.704634
1  367  1825.998871
2  368  1246.661929
3  369  1067.359745
4  370  2349.727614

In [38]:
df=pd.DataFrame(submission)

In [39]:
df['cnt']=y2_pred

In [40]:
df

id          cnt
0    366  1568.469697
1    367  1553.250000
2    368  1460.694118
3    369  1568.469697
4    370  1568.469697
..   ...          ...
361  727  1641.333333
362  728  1735.000000
363  729  1458.754098
364  730  1641.333333
365  731  1655.790323

[366 rows x 2 columns]

In [41]:
print(df.to_string(index=False))

  id          cnt
 366  1568.469697
 367  1553.250000
 368  1460.694118
 369  1568.469697
 370  1568.469697
 371  1849.756098
 372  1964.687500
 373  1768.108108
 374  1340.800000
 375  1821.142857
 376  1245.568627
 377  1460.694118
 378  1655.790323
 379  1641.333333
 380  1460.694118
 381  1460.694118
 382  1450.571429
 383  1568.857143
 384  1541.833333
 385  1651.152174
 386  1217.372881
 387  1142.777778
 388  1219.826087
 389  1528.476190
 390  1568.857143
 391  1655.790323
 392  2255.911765
 393  1915.250000
 394  1571.937500
 395  1611.617021
 396  1758.125000
 397  3993.770000
 398  1987.042857
 399  1933.562500
 400  1373.650000
 401  1324.227273
 402  1655.790323
 403  1849.756098
 404  1373.650000
 405  1641.333333
 406  1696.848485
 407   908.153846
 408  1622.270833
 409  1641.333333
 410  1847.460317
 411  1849.756098
 412  1752.421053
 413  1987.042857
 414  1959.148148
 415  1641.333333
 416  1641.333333
 417  1655.790323
 418  2163.185185
 419  3166.855346
 420  2557

In [43]:
df.to_csv('C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\adaboost_submission1.csv',index=False)