In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [68]:
dataset_train=pd.read_csv("C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\train.csv")
dataset_train.head()

id  season  mnth  holiday  weekday  workingday  weathersit      temp  \
0   1       1     1        0        6           0           2  0.344167   
1   2       1     1        0        0           0           2  0.363478   
2   3       1     1        0        1           1           1  0.196364   
3   4       1     1        0        2           1           1  0.200000   
4   5       1     1        0        3           1           1  0.226957   

      atemp       hum  windspeed   cnt  
0  0.363625  0.805833   0.160446   985  
1  0.353739  0.696087   0.248539   801  
2  0.189405  0.437273   0.248309  1349  
3  0.212122  0.590435   0.160296  1562  
4  0.229270  0.436957   0.186900  1600

In [69]:
del dataset_train[dataset_train.columns[0]]
dataset_train.head()

season  mnth  holiday  weekday  workingday  weathersit      temp     atemp  \
0       1     1        0        6           0           2  0.344167  0.363625   
1       1     1        0        0           0           2  0.363478  0.353739   
2       1     1        0        1           1           1  0.196364  0.189405   
3       1     1        0        2           1           1  0.200000  0.212122   
4       1     1        0        3           1           1  0.226957  0.229270   

        hum  windspeed   cnt  
0  0.805833   0.160446   985  
1  0.696087   0.248539   801  
2  0.437273   0.248309  1349  
3  0.590435   0.160296  1562  
4  0.436957   0.186900  1600

In [70]:
X = dataset_train.iloc[:, :-1].values
y = dataset_train.iloc[:, -1].values

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [81]:
y

array([ 985,  801, 1349, 1562, 1600, 1606, 1510,  959,  822, 1321, 1263,
       1162, 1406, 1421, 1248, 1204, 1000,  683, 1650, 1927, 1543,  981,
        986, 1416, 1985,  506,  431, 1167, 1098, 1096, 1501, 1360, 1526,
       1550, 1708, 1005, 1623, 1712, 1530, 1605, 1538, 1746, 1472, 1589,
       1913, 1815, 2115, 2475, 2927, 1635, 1812, 1107, 1450, 1917, 1807,
       1461, 1969, 2402, 1446, 1851, 2134, 1685, 1944, 2077,  605, 1872,
       2133, 1891,  623, 1977, 2132, 2417, 2046, 2056, 2192, 2744, 3239,
       3117, 2471, 2077, 2703, 2121, 1865, 2210, 2496, 1693, 2028, 2425,
       1536, 1685, 2227, 2252, 3249, 3115, 1795, 2808, 3141, 1471, 2455,
       2895, 3348, 2034, 2162, 3267, 3126,  795, 3744, 3429, 3204, 3944,
       4189, 1683, 4036, 4191, 4073, 4400, 3872, 4058, 4595, 5312, 3351,
       4401, 4451, 2633, 4433, 4608, 4714, 4333, 4362, 4803, 4182, 4864,
       4105, 3409, 4553, 3958, 4123, 3855, 4575, 4917, 5805, 4660, 4274,
       4492, 4978, 4677, 4679, 4758, 4788, 4098, 39

In [83]:
len(y_train)

292

In [74]:
len(X_test)

73

In [75]:
len(y_test)

73

In [88]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X,y)

DecisionTreeRegressor(random_state=0)

In [101]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)

In [102]:
y_pred

array([3744., 4511., 1815.,  431., 2471., 3523., 2227., 4205., 4334.,
       1510., 3351., 4660., 4352., 3644., 2659., 4475., 4308., 2034.,
       4780., 5805., 4274., 4541., 1851., 4304., 3331., 4713.,  623.,
       2914., 4191., 4086., 4433., 2162., 1204., 1712., 1807., 1606.,
       2134., 4105., 4795.,  605., 4590., 3669., 4266., 4274., 1543.,
       4186., 4845., 3574., 4634., 1872., 4790., 4602., 5130., 4891.,
       3249., 1461., 1450., 3958., 1685., 3239., 2566., 3907.,  959.,
       3348., 1495., 3620., 1969., 4451., 4326., 3915., 2192., 4010.,
       4073.])

In [103]:
print("training score : ", linear_regression.score(X_train, y_train))

training score :  0.7599634745571398


In [104]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)
print("Testing score : ", score)

Testing score :  1.0


In [95]:
dataset_test=pd.read_csv("C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\test.csv")
dataset_test.head()

id  season  mnth  holiday  weekday  workingday  weathersit      temp  \
0  366       1     1        0        0           0           1  0.370000   
1  367       1     1        1        1           0           1  0.273043   
2  368       1     1        0        2           1           1  0.150000   
3  369       1     1        0        3           1           2  0.107500   
4  370       1     1        0        4           1           1  0.265833   

      atemp       hum  windspeed  
0  0.375621  0.692500   0.192167  
1  0.252304  0.381304   0.329665  
2  0.126275  0.441250   0.365671  
3  0.119337  0.414583   0.184700  
4  0.278412  0.524167   0.129987

In [96]:
X2 = dataset_test.iloc[:, 1:].values

In [100]:
len(X2)

366

In [105]:
y2_pred = regressor.predict(X2)
np.set_printoptions(precision=2)

In [106]:
y2_pred

array([ 801., 1204., 1321., 1406., 1927., 1927., 1248., 1204.,  683.,
       1985., 1650., 1650., 1927.,  986.,  986., 1248.,  801., 1927.,
       1562., 1600.,  431.,  506.,  683.,  801., 1985., 1650., 1167.,
       1248., 1204., 1927., 1927., 2927., 1807., 1589., 1461., 1107.,
       1623., 2115., 1526., 1917., 1807., 1461., 1530., 1450., 1107.,
       2115., 1526., 2115., 2115., 1107., 1812., 1623., 1913., 3744.,
       1461., 1815., 1812., 2402., 2115., 1526., 3117., 2209., 2744.,
       2425., 1944., 2028., 2209., 3239., 2808., 2425., 3249., 3117.,
       3239., 3239., 3239., 2475., 3204., 3204., 3239., 3239., 3204.,
       3239., 3767., 3204., 2703., 2703., 2496., 3117., 3117., 2209.,
       2192., 2744., 2660., 3115., 3267., 3126., 2808., 3126., 3115.,
       3115., 2660., 2134., 2808., 3141., 5312., 4073., 4400., 4400.,
       3520., 3429., 5312., 5312., 2077., 1872., 2808., 3267., 3204.,
       3744., 3249., 3744., 3520., 4451., 4182., 3907., 4917., 4727.,
       4553., 4539.,

In [107]:
submission=pd.read_csv("C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\sample_submission.csv")
submission.head()

id          cnt
0  366  2324.704634
1  367  1825.998871
2  368  1246.661929
3  369  1067.359745
4  370  2349.727614

In [108]:
df=pd.DataFrame(submission)


In [109]:
df['cnt']=y2_pred

In [110]:
df

id     cnt
0    366   801.0
1    367  1204.0
2    368  1321.0
3    369  1406.0
4    370  1927.0
..   ...     ...
361  727  2302.0
362  728   754.0
363  729  2133.0
364  730  2302.0
365  731   754.0

[366 rows x 2 columns]

In [111]:
print(df.to_string(index=False))

  id     cnt
 366   801.0
 367  1204.0
 368  1321.0
 369  1406.0
 370  1927.0
 371  1927.0
 372  1248.0
 373  1204.0
 374   683.0
 375  1985.0
 376  1650.0
 377  1650.0
 378  1927.0
 379   986.0
 380   986.0
 381  1248.0
 382   801.0
 383  1927.0
 384  1562.0
 385  1600.0
 386   431.0
 387   506.0
 388   683.0
 389   801.0
 390  1985.0
 391  1650.0
 392  1167.0
 393  1248.0
 394  1204.0
 395  1927.0
 396  1927.0
 397  2927.0
 398  1807.0
 399  1589.0
 400  1461.0
 401  1107.0
 402  1623.0
 403  2115.0
 404  1526.0
 405  1917.0
 406  1807.0
 407  1461.0
 408  1530.0
 409  1450.0
 410  1107.0
 411  2115.0
 412  1526.0
 413  2115.0
 414  2115.0
 415  1107.0
 416  1812.0
 417  1623.0
 418  1913.0
 419  3744.0
 420  1461.0
 421  1815.0
 422  1812.0
 423  2402.0
 424  2115.0
 425  1526.0
 426  3117.0
 427  2209.0
 428  2744.0
 429  2425.0
 430  1944.0
 431  2028.0
 432  2209.0
 433  3239.0
 434  2808.0
 435  2425.0
 436  3249.0
 437  3117.0
 438  3239.0
 439  3239.0
 440  3239.0
 441  2475.0

In [112]:
df.to_csv('C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\DecisionTree_submission1.csv',index=False)