In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
dataset_train=pd.read_csv("C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\train.csv")
dataset_train.head()

id  season  mnth  holiday  weekday  workingday  weathersit      temp  \
0   1       1     1        0        6           0           2  0.344167   
1   2       1     1        0        0           0           2  0.363478   
2   3       1     1        0        1           1           1  0.196364   
3   4       1     1        0        2           1           1  0.200000   
4   5       1     1        0        3           1           1  0.226957   

      atemp       hum  windspeed   cnt  
0  0.363625  0.805833   0.160446   985  
1  0.353739  0.696087   0.248539   801  
2  0.189405  0.437273   0.248309  1349  
3  0.212122  0.590435   0.160296  1562  
4  0.229270  0.436957   0.186900  1600

In [19]:
del dataset_train[dataset_train.columns[0]]
dataset_train.head()

season  mnth  holiday  weekday  workingday  weathersit      temp     atemp  \
0       1     1        0        6           0           2  0.344167  0.363625   
1       1     1        0        0           0           2  0.363478  0.353739   
2       1     1        0        1           1           1  0.196364  0.189405   
3       1     1        0        2           1           1  0.200000  0.212122   
4       1     1        0        3           1           1  0.226957  0.229270   

        hum  windspeed   cnt  
0  0.805833   0.160446   985  
1  0.696087   0.248539   801  
2  0.437273   0.248309  1349  
3  0.590435   0.160296  1562  
4  0.436957   0.186900  1600

In [20]:
X = dataset_train.iloc[:, :-1].values
y = dataset_train.iloc[:, -1].values

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [22]:
X

array([[ 1.  ,  1.  ,  0.  , ...,  0.36,  0.81,  0.16],
       [ 1.  ,  1.  ,  0.  , ...,  0.35,  0.7 ,  0.25],
       [ 1.  ,  1.  ,  0.  , ...,  0.19,  0.44,  0.25],
       ...,
       [ 1.  , 12.  ,  0.  , ...,  0.26,  0.57,  0.12],
       [ 1.  , 12.  ,  0.  , ...,  0.32,  0.64,  0.13],
       [ 1.  , 12.  ,  0.  , ...,  0.41,  0.62,  0.22]])

In [23]:
len(y_train)

292

In [24]:
len(X_test)

73

In [25]:
len(y_test)

73

In [26]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X,y)

RandomForestRegressor(random_state=0)

In [27]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)

In [28]:
y_pred

array([3599.84, 4320.46, 1846.36,  647.16, 2291.67, 3511.38, 2146.29,
       4123.7 , 4452.86, 1514.3 , 3386.93, 4574.38, 4122.45, 3793.27,
       3004.86, 4423.64, 4257.89, 2595.7 , 4763.59, 5407.34, 4172.77,
       4446.33, 1894.82, 4119.47, 3450.51, 4720.41, 1294.42, 3027.73,
       3960.32, 4182.7 , 4190.91, 2240.23, 1224.88, 1751.09, 1772.19,
       1537.87, 2116.68, 4009.19, 4207.43,  863.01, 4583.4 , 3669.72,
       4400.26, 4353.24, 1443.13, 3936.05, 4697.74, 3903.05, 4709.15,
       1807.77, 4581.96, 4475.4 , 5006.26, 4936.38, 2910.25, 1553.59,
       1504.69, 4189.46, 1388.71, 3355.54, 2765.89, 4016.79,  992.79,
       3565.05, 2234.76, 3613.76, 1848.98, 4238.52, 4387.25, 3986.11,
       2122.4 , 4203.56, 4023.86])

In [29]:
dataset_test=pd.read_csv("C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\test.csv")
dataset_test.head()

id  season  mnth  holiday  weekday  workingday  weathersit      temp  \
0  366       1     1        0        0           0           1  0.370000   
1  367       1     1        1        1           0           1  0.273043   
2  368       1     1        0        2           1           1  0.150000   
3  369       1     1        0        3           1           2  0.107500   
4  370       1     1        0        4           1           1  0.265833   

      atemp       hum  windspeed  
0  0.375621  0.692500   0.192167  
1  0.252304  0.381304   0.329665  
2  0.126275  0.441250   0.365671  
3  0.119337  0.414583   0.184700  
4  0.278412  0.524167   0.129987

In [30]:
X2 = dataset_test.iloc[:, 1:].values

In [31]:
len(X2)

366

In [32]:
y2_pred = regressor.predict(X2)
np.set_printoptions(precision=2)

In [33]:
y2_pred

array([1283.45, 1243.42, 1362.56, 1409.72, 1859.56, 1819.42, 1532.85,
       1434.87, 1198.24, 1765.66, 1214.86, 1350.37, 1757.46, 1063.03,
        979.5 , 1056.64, 1280.21, 1787.77, 1424.32, 1603.  ,  842.66,
        810.15,  917.3 , 1250.4 , 1731.33, 1356.49, 1694.09, 1420.42,
       1368.43, 1824.92, 1856.82, 3392.21, 1932.03, 1853.45, 1582.47,
       1406.23, 1747.35, 2021.13, 1682.94, 1826.91, 1865.66, 1211.67,
       1362.26, 1707.19, 1900.62, 2030.51, 1815.56, 2020.58, 1960.77,
       1615.31, 1633.34, 1761.24, 1965.75, 2817.97, 2172.16, 1773.97,
       1796.49, 1945.49, 2033.4 , 1734.51, 3294.34, 2101.13, 2452.53,
       1982.69, 1839.02, 1945.8 , 2055.82, 3158.23, 1870.05, 2076.96,
       2313.56, 3563.88, 3475.48, 3611.5 , 3391.22, 2773.47, 3653.75,
       3417.57, 3319.93, 3442.24, 3634.  , 3594.36, 3964.49, 3495.97,
       2632.41, 2835.29, 2263.77, 3536.36, 3482.59, 2234.52, 2442.7 ,
       2786.03, 3069.77, 3820.01, 3899.15, 3213.55, 2686.01, 3215.09,
       3832.34, 3427

In [34]:
submission=pd.read_csv("C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\sample_submission.csv")
submission.head()

id          cnt
0  366  2324.704634
1  367  1825.998871
2  368  1246.661929
3  369  1067.359745
4  370  2349.727614

In [35]:
df=pd.DataFrame(submission)


In [36]:
df['cnt']=y2_pred

In [37]:
df

id      cnt
0    366  1283.45
1    367  1243.42
2    368  1362.56
3    369  1409.72
4    370  1859.56
..   ...      ...
361  727  1865.76
362  728  2024.87
363  729  1756.99
364  730  1688.33
365  731  1708.26

[366 rows x 2 columns]

In [38]:
print(df.to_string(index=False))

  id      cnt
 366  1283.45
 367  1243.42
 368  1362.56
 369  1409.72
 370  1859.56
 371  1819.42
 372  1532.85
 373  1434.87
 374  1198.24
 375  1765.66
 376  1214.86
 377  1350.37
 378  1757.46
 379  1063.03
 380   979.50
 381  1056.64
 382  1280.21
 383  1787.77
 384  1424.32
 385  1603.00
 386   842.66
 387   810.15
 388   917.30
 389  1250.40
 390  1731.33
 391  1356.49
 392  1694.09
 393  1420.42
 394  1368.43
 395  1824.92
 396  1856.82
 397  3392.21
 398  1932.03
 399  1853.45
 400  1582.47
 401  1406.23
 402  1747.35
 403  2021.13
 404  1682.94
 405  1826.91
 406  1865.66
 407  1211.67
 408  1362.26
 409  1707.19
 410  1900.62
 411  2030.51
 412  1815.56
 413  2020.58
 414  1960.77
 415  1615.31
 416  1633.34
 417  1761.24
 418  1965.75
 419  2817.97
 420  2172.16
 421  1773.97
 422  1796.49
 423  1945.49
 424  2033.40
 425  1734.51
 426  3294.34
 427  2101.13
 428  2452.53
 429  1982.69
 430  1839.02
 431  1945.80
 432  2055.82
 433  3158.23
 434  1870.05
 435  2076.96
 436  

In [39]:
df.to_csv('C:\\Users\\jonathan.sh\\OneDrive - Webpals\\DS Course\\Task DS\\RandomForest_submission1.csv',index=False)